server {
    listen 80;

    # Onde os arquivos do build (dist) estarão armazenados
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        # Tenta servir o arquivo solicitado, se não existir envia para o index.html (importante para SPAs como o React)
        try_files $uri $uri/ /index.html;
    }

    # Tratamento de erro
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
